# dibuat oleh tools/build_assets.py: <id>=<jumlah frame>,<durasi per frame (ms)>
buckethead=64,69
cherrybomb=8,110
conehead=63,50
dolphin=5,68
duckytube=1,80
duckytube_cone=1,80
football=29,40
football_dying=6,100
fumeshroom=1,1000
jalapeno=6,110
lawnmower=2,200
lilypad=60,30
newspaper=51,30
pea=1,80
peashooter=49,30
polevault=21,66
potatomine=2,450
potatomine_unarmed=1,1000
puff_bullet=1,80
puffshroom=1,80
repeater=49,30
snorkel=46,30
snowpea=1,80
snowpea_bullet=1,80
squash=50,30
sun=3,200
sunflower=55,30
sunshroom=1,1000
tallnut=14,90
tallnut_cracked1=13,118
tallnut_cracked2=12,112
tanglekelp=17,100
wallnut=1,80
wallnut_cracked1=1,80
wallnut_cracked2=1,80
zombie=64,99
zombie_dying=6,183
zombie_head=1,1000
